### ISSUE TITLE
Это не UTF-8

### ISSUE THREAD

**Issue by andrey-ilyin** [NikolaiNikollski/TrevelLine#1]
https://github.com/NikolaiNikollski/TrevelLine/blob/bb4b6dc85fe3b96ad81c7f0cf6bad48974122d54/Lw0/Lw0.txt#L1

**Comment by NikolaiNikollski** [comment]
Не понял... =(
символы их номеру юникода соответствуют...
Может, проблема в пробеле между байтами?

041d 0438 0430 043e 043b 044c 0441 043a

**Comment by andrey-ilyin** [comment]
Здесь похоже UTF-16. 
![sample](https://user-images.githubusercontent.com/7816323/88029744-10017600-cb43-11ea-8973-0cc0789c104b.png)

**Comment by andrey-ilyin** [comment]
В кодировке UTF-8 сообщение выглядит так:
![image](https://user-images.githubusercontent.com/7816323/88029850-2e677180-cb43-11ea-8c92-6eace708ca16.png)

**Comment by andrey-ilyin** [comment]
Обрати внимание, 1) каждый символ кодируется 2-мя байтами, 2) каждый символ начинается либо с D0, либо с D1. 
Это характерная особенность кодировки UTF-8 для кириллических символов.

**Comment by NikolaiNikollski** [comment]
Исправил

**Comment by andrey-ilyin** [comment]
Принято.
