### ISSUE TITLE
Требуется уточнение

### ISSUE THREAD

**Issue by andrey-ilyin** [NikolaiNikollski/TrevelLine#10]
https://github.com/NikolaiNikollski/TrevelLine/blob/86b878bf915d4b70b9e33a6218dbc379b505913d/Lw1/Lw1.txt#L46

Существуют разные способы сообщить браузеру верную кодировку:
* Указать HTTP заголовок Content-Type
* В теле html докумнета добавить мета тэг <charset> 
* Передавать в теле ответа BOM

Прошу углубиться в вопрос и описать, как работает каждый из указанных методов.

**Comment by NikolaiNikollski** [comment]
Существует несколько способов исправить ситуацию:
1)Указать HTTP заголовок Content-Type .
  Можно на сервере добавить кодировку по умолчанию utf-8
  тогда он добавит заголовок Content-Type параметр charset
2)В теле html документа добавить мета тэг.
  Ответ сервера по прежнему не будет содержать параметра charset,
  но браузер определит кодировку благодаря благодаря подсказке
3)Передавать в теле ответа BOM.
  Можно html документ перевести в кодировку с BOM,
  результат аналогичен п.2.

**Comment by andrey-ilyin** [comment]
Принято.
