### ISSUE TITLE
Механизм удаления лишних пробелов надо вынести в отдельную функцию

### ISSUE THREAD

**Issue by andrey-ilyin** [NikolaiNikollski/TrevelLine#11]
https://github.com/NikolaiNikollski/TrevelLine/blob/86b878bf915d4b70b9e33a6218dbc379b505913d/Lw2/3/remove_duplicates.cs#L21

**Comment by NikolaiNikollski** [comment]
Сделано.

**Comment by andrey-ilyin** [comment]
Принято.
