### ISSUE TITLE
Упростить выражение if

### ISSUE THREAD

**Issue by andrey-ilyin** [NikolaiNikollski/TrevelLine#12]
https://github.com/NikolaiNikollski/TrevelLine/blob/86b878bf915d4b70b9e33a6218dbc379b505913d/Lw2/3/remove_duplicates.cs#L10

Какие есть проблемы у текущего решения:
1) большая вложенность
2) громоздкий блок if

Прошу упростить. 
Можно посмотреть, что предлагает Роберт Матрин в книге Чистый код.

**Comment by NikolaiNikollski** [comment]
заменил блок if на switch,
надеюсь, так лучше

**Comment by andrey-ilyin** [comment]
Ок. Стало лучше. 

Можно еще применить такой подход. В самом начале функции проверить передаваемые переменные. И если они не соотвествуют контракту (ожидаемому значению) выйти из функции при помощи return.
Что это дает:
1) Проверка на ошибку и обработка ошибки рядом.
2) Отствует вложенность
3) Более линейная структура кода.

        static void Main(string[] args)
        {
            if (args.Length == 0)
            {
                Console.WriteLine("No parameters were specified!");
                return;
            }

            if (args.Length > 1)
            {
                Console.WriteLine("Incorrect number of arguments!");
                Console.WriteLine("Usage remove_duplicates.exe <input string>");
                return;
            }

            Console.WriteLine( removeDuplicates(args[0]) );
       }
