### ISSUE TITLE
Использовать стандарт форматирования

### ISSUE THREAD

**Issue by andrey-ilyin** [NikolaiNikollski/TrevelLine#13]
https://github.com/NikolaiNikollski/TrevelLine/blob/86b878bf915d4b70b9e33a6218dbc379b505913d/Lw2/3/remove_duplicates.cs#L4

В задании лабораторной работы есть файл .editorconfig, который настраивает правила для автоформатирования. 
Почему-то в lw2 он возможно не применился. 

Идентификатор для namespace должен быть записан в CamelCase.

**Comment by NikolaiNikollski** [comment]
Впредь буду использовать .editorconfig.
namespace был переписан в CamelCase.

**Comment by andrey-ilyin** [comment]
Принято.
