### ISSUE TITLE
Добавить в gitignore файлы - результаты билда проекта

### ISSUE THREAD

**Issue by andrey-ilyin** [NikolaiNikollski/TrevelLine#14]
![gitignore](https://user-images.githubusercontent.com/7816323/88674853-fc31b300-d0f2-11ea-9f92-aaef0fc4553d.png)

**Comment by andrey-ilyin** [comment]
.vs тоже

**Comment by andrey-ilyin** [comment]
Можно сделать один .gitignore на весь репозиторий.

**Comment by NikolaiNikollski** [comment]
Добавил

**Comment by andrey-ilyin** [comment]
Принято.
