### ISSUE TITLE
Один файл - один namespace

### ISSUE THREAD

**Issue by andrey-ilyin** [NikolaiNikollski/TrevelLine#15]
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/7816323/88675038-300cd880-d0f3-11ea-8787-f11f3aa546c6.png)

Тут в 1 файле 2 namespace почему то еще. Обычно 1  файл - 1 класс и 1 namespace.

**Comment by NikolaiNikollski** [comment]
исправил

**Comment by andrey-ilyin** [comment]
Принято.
