### ISSUE TITLE
Название namespace'ов должно быть с заглавной буквы.

### ISSUE THREAD

**Issue by andrey-ilyin** [NikolaiNikollski/TrevelLine#19]
https://github.com/NikolaiNikollski/TrevelLine/blob/28e91f568fafdae5781426bcc16c5cbb839a2d0f/Lw3/1/checkIdentifierTests/UnitTest1.cs#L4

**Comment by NikolaiNikollski** [comment]
исправил

**Comment by andrey-ilyin** [comment]
Принято.
