### ISSUE TITLE
Использовать .gitignore

### ISSUE THREAD

**Issue by andrey-ilyin** [NikolaiNikollski/TrevelLine#2]
В репозитории не надо хранить временные файлы, а так же служебные файлы, которые создаются при компиляции или обработке чего-либо.

Сейчас речь идет о файле 4.o
Дальше будут проекты, которые нужно будет создавать в Visual Studio. Там мусора будет значительно больше.
Репозиторий надо содержать в чистоте.

Можно либо вручную удалять такие файлы каждый раз перед коммитом.
А можно еще дополнительно задействовать механизм .gitignore. О нем загугли.

**Comment by andrey-ilyin** [comment]
4.exe тоже лишний файл в репозиторит

**Comment by andrey-ilyin** [comment]
fp___.err
fp___.out
тоже

**Comment by NikolaiNikollski** [comment]
лишних и служебных файлов больше нет в репозитории

**Comment by andrey-ilyin** [comment]
Принято.
