### ISSUE TITLE
После завершения работы с файлами файл надо закрыть

### ISSUE THREAD

**Issue by andrey-ilyin** [NikolaiNikollski/TrevelLine#4]
https://github.com/NikolaiNikollski/TrevelLine/blob/bb4b6dc85fe3b96ad81c7f0cf6bad48974122d54/Lw0/4/4.pas#L80

Надо использовать процедуру CLOSE после завершения работы с файлом.
В дальнейшем такую же практику надо будет применять и при работе с другими технологиями:
при работе с базой, с сокетами... да вообще с чем угодно.

**Comment by NikolaiNikollski** [comment]
Понял, принял, буду знать.
CLOSE(OUTPUT)

**Comment by andrey-ilyin** [comment]
Принято.
