### ISSUE TITLE
Добавить проверку результата выполнения команды REWRITE

### ISSUE THREAD

**Issue by andrey-ilyin** [NikolaiNikollski/TrevelLine#5]
https://github.com/NikolaiNikollski/TrevelLine/blob/bb4b6dc85fe3b96ad81c7f0cf6bad48974122d54/Lw0/4/4.pas#L69

Команда REWRITE может завершиться с ошибкой. 
Надо выработать привычку - проверять результаты выполнения функций.

**Comment by NikolaiNikollski** [comment]
Не знал, что REWRITE может завершиться ошибкой и функцию IORESULT,
буду иметь ввиду
  
ASSIGN(OUTPUT, 'output.txt');
  {$I-}
    REWRITE(OUTPUT);
  {$I+}
  IF IORESULT = 0
  THEN

**Comment by andrey-ilyin** [comment]
Принято.
