### ISSUE TITLE
В слове cache опечатка

### ISSUE THREAD

**Issue by andrey-ilyin** [NikolaiNikollski/TrevelLine#6]
https://github.com/NikolaiNikollski/TrevelLine/blob/86b878bf915d4b70b9e33a6218dbc379b505913d/Lw1/Lw1.txt#L25

**Comment by NikolaiNikollski** [comment]
Исправил

**Comment by andrey-ilyin** [comment]
Сейчас тоже с опечаткой.

**Comment by NikolaiNikollski** [comment]
Исправил =(

**Comment by andrey-ilyin** [comment]
Принято.
