### ISSUE TITLE
Улучшить работу с GitHub

### ISSUE THREAD

**Issue by andrey-ilyin** [NikolaiNikollski/TrevelLine#8]
1. Коммиты лучше делать для логически связанных изменений. 
Например, для каждого задания из lw2 можно сделать отдельный коммит.
Для исправления одного issue - один коммит. 

2. У каждого коммита надо писать понятный текст пояснения. Писать надо на русском языке. 

По данной issue в существующий репозиторий правки вносить не надо. Отпишись, что прочитал, закрою.

**Comment by NikolaiNikollski** [comment]
Прочитал.

**Comment by andrey-ilyin** [comment]
Принято.
