### ISSUE TITLE
Требуется уточнение

### ISSUE THREAD

**Issue by andrey-ilyin** [NikolaiNikollski/TrevelLine#9]
https://github.com/NikolaiNikollski/TrevelLine/blob/86b878bf915d4b70b9e33a6218dbc379b505913d/Lw1/Lw1.txt#L43

Веб сервер не определяет кодировку. Фактически он просто передатчик. Какие данные пришли от приложения, он передает дальше. Определение кодировки происходит в браузере. 

Прошу перечитать статью Что на самом деле происходит...

**Comment by NikolaiNikollski** [comment]
Статью перечитал, она достаточно сложная... 
Задание 3 исправил.

3)
Параметр charset у заголовка Content-Type требуется для определения кодировки. 
Если charset будет не задан или будет задан не верно, то результат будет зависеть от браузера.
Браузер может сам понять, какая нужна кодировка, в противном случае пользователь увидит нечитаемый текст
 
в примере  http://localhost/lw1/all_begin_from_http.html

nginx в теле ответа не указывает параметр charset у заголовка Content-Type,
браузер не может определить кодировку, видим нечитаемый текст

Существует несколько способов исправить ситуацию:
1)Указать HTTP заголовок Content-Type .
  Можно на сервере добавить кодировку по умолчанию utf-8
  тогда он добавит заголовок Content-Type параметр charset
2)В теле html документа добавить мета тэг.
  Ответ сервера по прежнему не будет содержать параметра charset,
  но браузер определит кодировку благодаря благодаря подсказке
3)Передавать в теле ответа BOM.
  Можно html документ перевести в кодировку с BOM,
  результат аналогичен п.2.

**Comment by andrey-ilyin** [comment]
Принято.
